//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UncommonSense.CBreeze.Core;
using System.Management.Automation;

// FIXME: For item nodes, allow AccessByPermission to be set directly, e.g. using New-CBreezeAccessByPermission

namespace UncommonSense.CBreeze.Automation 
{
	[Cmdlet(VerbsCommon.New, "CBreezeDeltaMenuSuiteNode", DefaultParameterSetName="NewWithoutID")]
	[OutputType(typeof(DeltaNode))]
	[Alias("DeltaNode")]
	public class NewCBreezeDeltaMenuSuiteNode : NewItemWithIDCmdlet<DeltaNode, Guid, MenuSuite>
	{
		protected override IEnumerable<DeltaNode> CreateItems() 
		{
			var deltaNode = new DeltaNode(ID);	
			deltaNode.Properties.Deleted = NullableBooleanFromSwitch(nameof(Deleted));
			deltaNode.Properties.NextNodeID = NextNodeID;
			yield return deltaNode;
		}

		protected override void AddItemToInputObject(DeltaNode item, MenuSuite inputObject)
		{
            if (!inputObject.Nodes.Any())
            {
                var deltaNode = inputObject.Nodes.Add(new DeltaNode(Guid.NewGuid()));
                deltaNode.Properties.NextNodeID = item.ID;
            }

            inputObject.Nodes.Add(item);
		}

		[Parameter()]
		public SwitchParameter Deleted 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> NextNodeID 
		{
			get; set;
		}

	}

	[Cmdlet(VerbsCommon.New, "CBreezeGroupMenuSuiteNode", DefaultParameterSetName="NewWithoutID")]
	[OutputType(typeof(GroupNode))]
	[Alias("GroupNode")]
	public class NewCBreezeGroupMenuSuiteNode : NewItemWithIDCmdlet<GroupNode, Guid, MenuSuite>
	{
		protected override IEnumerable<GroupNode> CreateItems() 
		{
			var groupNode = new GroupNode(ID);	
			groupNode.Properties.Deleted = NullableBooleanFromSwitch(nameof(Deleted));
			groupNode.Properties.FirstChild = FirstChild;
			groupNode.Properties.IsDepartmentPage = NullableBooleanFromSwitch(nameof(IsDepartmentPage));
			groupNode.Properties.MemberOfMenu = MemberOfMenu;
			groupNode.Properties.Name = Name;
			groupNode.Properties.NextNodeID = NextNodeID;
			groupNode.Properties.ParentNodeID = ParentNodeID;
			groupNode.Properties.Visible = NullableBooleanFromSwitch(nameof(Visible));
			groupNode.Properties.CaptionML.Set(CaptionML);
			yield return groupNode;
		}

		protected override void AddItemToInputObject(GroupNode item, MenuSuite inputObject)
		{
            if (!inputObject.Nodes.Any())
            {
                var deltaNode = inputObject.Nodes.Add(new DeltaNode(Guid.NewGuid()));
                deltaNode.Properties.NextNodeID = item.ID;
            }

            inputObject.Nodes.Add(item);
		}

		[Parameter()]
		public SwitchParameter Deleted 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> FirstChild 
		{
			get; set;
		}

		[Parameter()]
		public SwitchParameter IsDepartmentPage 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> MemberOfMenu 
		{
			get; set;
		}

		[Parameter()]
		public String Name 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> NextNodeID 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> ParentNodeID 
		{
			get; set;
		}

		[Parameter()]
		public SwitchParameter Visible 
		{
			get; set;
		}

		[Parameter(Mandatory = true, Position = 1, ParameterSetName = ParameterSetNames.NewWithoutID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.NewWithID)]
		[Parameter(Mandatory = true, Position = 1, ParameterSetName = ParameterSetNames.AddWithoutID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.AddWithID)]
		public Hashtable CaptionML 
		{
			get; set;
		}

	}

	[Cmdlet(VerbsCommon.New, "CBreezeItemMenuSuiteNode", DefaultParameterSetName="NewWithoutID")]
	[OutputType(typeof(ItemNode))]
	[Alias("ItemNode")]
	public class NewCBreezeItemMenuSuiteNode : NewItemWithIDCmdlet<ItemNode, Guid, MenuSuite>
	{
		protected override IEnumerable<ItemNode> CreateItems() 
		{
			var itemNode = new ItemNode(ID);	
			itemNode.Properties.Deleted = NullableBooleanFromSwitch(nameof(Deleted));
			itemNode.Properties.DepartmentCategory = DepartmentCategory;
			itemNode.Properties.MemberOfMenu = MemberOfMenu;
			itemNode.Properties.Name = Name;
			itemNode.Properties.NextNodeID = NextNodeID;
			itemNode.Properties.ParentNodeID = ParentNodeID;
			itemNode.Properties.Visible = NullableBooleanFromSwitch(nameof(Visible));
			itemNode.Properties.CaptionML.Set(CaptionML);
			itemNode.Properties.ApplicationArea.Set(ApplicationArea);
			itemNode.Properties.RunObjectType = RunObjectType;
			itemNode.Properties.RunObjectID = RunObjectID;
			yield return itemNode;
		}

		protected override void AddItemToInputObject(ItemNode item, MenuSuite inputObject)
		{
            if (!inputObject.Nodes.Any())
            {
                var deltaNode = inputObject.Nodes.Add(new DeltaNode(Guid.NewGuid()));
                deltaNode.Properties.NextNodeID = item.ID;
            }

            inputObject.Nodes.Add(item);
		}

		[Parameter()]
		public SwitchParameter Deleted 
		{
			get; set;
		}

		[Parameter(Mandatory=true)]
		public Nullable<MenuItemDepartmentCategory> DepartmentCategory 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> MemberOfMenu 
		{
			get; set;
		}

		[Parameter()]
		public String Name 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> NextNodeID 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> ParentNodeID 
		{
			get; set;
		}

		[Parameter()]
		public SwitchParameter Visible 
		{
			get; set;
		}

		[Parameter(Mandatory = true, Position = 1, ParameterSetName = ParameterSetNames.NewWithoutID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.NewWithID)]
		[Parameter(Mandatory = true, Position = 1, ParameterSetName = ParameterSetNames.AddWithoutID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.AddWithID)]
		public Hashtable CaptionML 
		{
			get; set;
		}

		[Parameter(Mandatory = true, Position = 1, ParameterSetName = ParameterSetNames.NewWithoutID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.NewWithID)]
		[Parameter(Mandatory = true, Position = 1, ParameterSetName = ParameterSetNames.AddWithoutID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.AddWithID)]
		public String[] ApplicationArea 
		{
			get; set;
		}

		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.NewWithoutID)]
		[Parameter(Mandatory = true, Position = 3, ParameterSetName = ParameterSetNames.NewWithID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.AddWithoutID)]
		[Parameter(Mandatory = true, Position = 3, ParameterSetName = ParameterSetNames.AddWithID)]
		public Nullable<MenuItemRunObjectType> RunObjectType 
		{
			get; set;
		}

		[Parameter(Mandatory = true, Position = 3, ParameterSetName = ParameterSetNames.NewWithoutID)]
		[Parameter(Mandatory = true, Position = 4, ParameterSetName = ParameterSetNames.NewWithID)]
		[Parameter(Mandatory = true, Position = 3, ParameterSetName = ParameterSetNames.AddWithoutID)]
		[Parameter(Mandatory = true, Position = 4, ParameterSetName = ParameterSetNames.AddWithID)]
		[ValidateRange(1, int.MaxValue)] 
		public Nullable<Int32> RunObjectID 
		{
			get; set;
		}

	}

	[Cmdlet(VerbsCommon.New, "CBreezeMenuMenuSuiteNode", DefaultParameterSetName="NewWithoutID")]
	[OutputType(typeof(MenuNode))]
	[Alias("MenuNode")]
	public class NewCBreezeMenuMenuSuiteNode : NewItemWithIDCmdlet<MenuNode, Guid, MenuSuite>
	{
		protected override IEnumerable<MenuNode> CreateItems() 
		{
			var menuNode = new MenuNode(ID);	
			menuNode.Properties.Enabled = NullableBooleanFromSwitch(nameof(Enabled));
			menuNode.Properties.FirstChild = FirstChild;
			menuNode.Properties.Image = Image;
			menuNode.Properties.IsShortcut = NullableBooleanFromSwitch(nameof(IsShortcut));
			menuNode.Properties.MemberOfMenu = MemberOfMenu;
			menuNode.Properties.Name = Name;
			menuNode.Properties.NextNodeID = NextNodeID;
			menuNode.Properties.ParentNodeID = ParentNodeID;
			menuNode.Properties.Visible = NullableBooleanFromSwitch(nameof(Visible));
			menuNode.Properties.CaptionML.Set(CaptionML);
			yield return menuNode;
		}

		protected override void AddItemToInputObject(MenuNode item, MenuSuite inputObject)
		{
            if (!inputObject.Nodes.Any())
            {
                var deltaNode = inputObject.Nodes.Add(new DeltaNode(Guid.NewGuid()));
                deltaNode.Properties.NextNodeID = item.ID;
            }

            inputObject.Nodes.Add(item);
		}

		[Parameter()]
		public SwitchParameter Enabled 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> FirstChild 
		{
			get; set;
		}

		[Parameter()]
		[ValidateRange(0, 15)] 
		public Nullable<Int32> Image 
		{
			get; set;
		}

		[Parameter()]
		public SwitchParameter IsShortcut 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> MemberOfMenu 
		{
			get; set;
		}

		[Parameter()]
		public String Name 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> NextNodeID 
		{
			get; set;
		}

		[Parameter()]
		public Nullable<Guid> ParentNodeID 
		{
			get; set;
		}

		[Parameter()]
		public SwitchParameter Visible 
		{
			get; set;
		}

		[Parameter(Mandatory = true, Position = 1, ParameterSetName = ParameterSetNames.NewWithoutID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.NewWithID)]
		[Parameter(Mandatory = true, Position = 1, ParameterSetName = ParameterSetNames.AddWithoutID)]
		[Parameter(Mandatory = true, Position = 2, ParameterSetName = ParameterSetNames.AddWithID)]
		public Hashtable CaptionML 
		{
			get; set;
		}

	}

	[Cmdlet(VerbsCommon.New, "CBreezeRootMenuSuiteNode", DefaultParameterSetName="NewWithoutID")]
	[OutputType(typeof(RootNode))]
	[Alias("RootNode")]
	public class NewCBreezeRootMenuSuiteNode : NewItemWithIDCmdlet<RootNode, Guid, MenuSuite>
	{
		protected override IEnumerable<RootNode> CreateItems() 
		{
			var rootNode = new RootNode(ID);	
			rootNode.Properties.FirstChild = FirstChild;
			yield return rootNode;
		}

		protected override void AddItemToInputObject(RootNode item, MenuSuite inputObject)
		{
            if (!inputObject.Nodes.Any())
            {
                var deltaNode = inputObject.Nodes.Add(new DeltaNode(Guid.NewGuid()));
                deltaNode.Properties.NextNodeID = item.ID;
            }

            inputObject.Nodes.Add(item);
		}

		[Parameter()]
		public Nullable<Guid> FirstChild 
		{
			get; set;
		}

	}

}

