// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public class ActionList : IntegerKeyedAndNamedContainer<PageActionBase>
    {
        // Ctor made public so that ActionListProperty can new this up
        public ActionList()
        {
        }

        public override void ValidateName(PageActionBase item)
        {
            TestNameUnique(item);
        }
    }
}
