// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

namespace UncommonSense.CBreeze.Core
{
    public enum AutoFormatType
    {
        Other,
        Amount,
        UnitAmount,
    }
}
