// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class BlobTableField : TableField
    {
        public BlobTableField(Int32 no, String name)
            : base(no, name)
        {
            Properties = new BlobTableFieldProperties();
        }

        public override TableFieldType Type
        {
            get
            {
                return TableFieldType.Blob;
            }
        }

        public BlobTableFieldProperties Properties
        {
            get;
            protected set;
        }

        public override Properties AllProperties
        {
            get
            {
                return Properties;
            }
        }
    }
}
