// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class CalcFormulaTableFilterLine
    {
        private string fieldName;
        private Boolean onlyMaxLimit;
        private TableFilterType? type;
        private string value;
        private Boolean valueIsFilter;

        public CalcFormulaTableFilterLine(string fieldName, TableFilterType type, string value)
        {
            this.fieldName = fieldName;
            this.type = type;
            this.value = value;
        }

        public string FieldName
        {
            get
            {
                return this.fieldName;
            }
        }

        public Boolean OnlyMaxLimit
        {
            get
            {
                return this.onlyMaxLimit;
            }
            set
            {
                this.onlyMaxLimit = value;
            }
        }

        public TableFilterType? Type
        {
            get
            {
                return this.type;
            }
        }

        public string Value
        {
            get
            {
                return this.value;
            }
        }

        public Boolean ValueIsFilter
        {
            get
            {
                return this.valueIsFilter;
            }
            set
            {
                this.valueIsFilter = value;
            }
        }

    }
}
