// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class Code
    {
        internal Code()
        {
            Documentation = new Documentation();
            Events = new Events();
            Functions = new Functions();
            Variables = new Variables();
        }

        public Documentation Documentation
        {
            get;
            protected set;
        }

        public Events Events
        {
            get;
            protected set;
        }

        public Functions Functions
        {
            get;
            protected set;
        }

        public Variables Variables
        {
            get;
            protected set;
        }
    }
}
