// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class ColumnReportElement : ReportElement
    {
        private ColumnReportElementProperties properties = new ColumnReportElementProperties();

        public ColumnReportElement(Int32 id, Int32? indentationLevel) : base(id, indentationLevel)
        {
        }

        public override ReportElementType Type
        {
            get
            {
                return ReportElementType.Column;
            }
        }

        public ColumnReportElementProperties Properties
        {
            get
            {
                return this.properties;
            }
        }

    }
}
