// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class ColumnFilterLine
    {
        private String column;
        private TableFilterType? type;
        private String value;

        internal ColumnFilterLine(String column, TableFilterType type, String value)
        {
            this.column = column;
            this.type = type;
            this.value = value;
        }

        public String Column
        {
            get
            {
                return this.column;
            }
        }

        public TableFilterType? Type
        {
            get
            {
                return this.type;
            }
        }

        public String Value
        {
            get
            {
                return this.value;
            }
        }

    }
}
