// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class ControlReference
    {
        private String controlName;

        internal ControlReference(String controlName)
        {
            this.controlName = controlName;
        }

        public String ControlName
        {
            get
            {
                return this.controlName;
            }
        }

    }
}
