// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public class DataItemQueryElementTableFilter : Collection<DataItemQueryElementTableFilterLine>
    {
        new public DataItemQueryElementTableFilterLine Add(DataItemQueryElementTableFilterLine value)
        {
            this.InsertItem(Count, value);
            return value;
        }

        public void AddRange(IEnumerable<DataItemQueryElementTableFilterLine> values)
        {
            foreach (var value in values)
            {
                this.Add(value);
            }
        }
    }
}
