// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class DecimalPlaces
    {
        private int? atLeast;
        private int? atMost;

        // Made ctor public so that DecimalPlacesProperty can new up a new instance
        public DecimalPlaces()
        {
        }

        public int? AtLeast
        {
            get
            {
                return this.atLeast;
            }
            set
            {
                this.atLeast = value;
            }
        }

        public int? AtMost
        {
            get
            {
                return this.atMost;
            }
            set
            {
                this.atMost = value;
            }
        }

    }
}
