// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class DotNetVariable : Variable
    {
        private string dimensions;
        private bool? runOnClient;
        private string subType;
        private bool? withEvents;

        public DotNetVariable(int id, string name, string subType) : base(id, name)
        {
            this.subType = subType;
        }

        public override VariableType Type
        {
            get
            {
                return VariableType.DotNet;
            }
        }

        public string Dimensions
        {
            get
            {
                return this.dimensions;
            }
            set
            {
                this.dimensions = value;
            }
        }

        public bool? RunOnClient
        {
            get
            {
                return this.runOnClient;
            }
            set
            {
                this.runOnClient = value;
            }
        }

        public string SubType
        {
            get
            {
                return this.subType;
            }
        }

        public bool? WithEvents
        {
            get
            {
                return this.withEvents;
            }
            set
            {
                this.withEvents = value;
            }
        }

    }
}
