// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class DotNetParameter : Parameter
    {
        private Boolean? runOnClient;
        private String subType;
        private Boolean? suppressDispose;

        public DotNetParameter(Boolean var, int id, String name, String subType) : base(var, id, name)
        {
            this.subType = subType;
        }

        public override ParameterType Type
        {
            get
            {
                return ParameterType.DotNet;
            }
        }

        public Boolean? RunOnClient
        {
            get
            {
                return this.runOnClient;
            }
            set
            {
                this.runOnClient = value;
            }
        }

        public String SubType
        {
            get
            {
                return this.subType;
            }
        }

        public Boolean? SuppressDispose
        {
            get
            {
                return this.suppressDispose;
            }
            set
            {
                this.suppressDispose = value;
            }
        }

    }
}
