// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public class Events : Collection<Event>
    {
        internal Events(Code code)
        {
            Code = code;
        }

        public Code Code
        {
            get;
            protected set;
        }

        public new Event Add(Event item)
        {
            base.Add(item);
            return item;
        }
    }
}
