mkdir Base
mkdir Code
mkdir Codeunit
mkdir Contracts
mkdir Extension
mkdir Generic
mkdir MenuSuite
mkdir Page
mkdir Properties
mkdir Property
mkdir Query
mkdir Report
mkdir Table
mkdir XmlPort
mkdir Base/Application
git mv Application.cs Base
git mv DefaultRanges.cs Base
git mv GuidKeyedContainer.cs Base
git mv IntegerKeyedAndNamedContainer.cs Base
git mv BaseApp.2015.cs Base/Application
git mv BaseApp.2016.cs Base/Application
git mv BaseApp.2017.cs Base/Application
git mv RunTime.2015.cs Base/Application
git mv RunTime.2016.cs Base/Application
git mv RunTime.2017.cs Base/Application
git mv Object.cs Base
mkdir Code/Function
mkdir Code/Parameter
mkdir Code/Variable
git mv CodeLines.cs Code
git mv Documentation.cs Code
git mv Events.cs Code
git mv EventPublisherSubscriber.cs Code/Function
git mv EventSubscriberInstance.cs Code/Function
git mv FunctionReturnValue.cs Code/Function
git mv Functions.cs Code/Function
git mv TestFunctionType.cs Code/Function
git mv TestIsolation.cs Code/Function
git mv UpgradeFunctionType.cs Code/Function
git mv ActionParameter.cs Code/Parameter
git mv AutomationParameter.cs Code/Parameter
git mv BigIntegerParameter.cs Code/Parameter
git mv BigTextParameter.cs Code/Parameter
git mv BinaryParameter.cs Code/Parameter
git mv BooleanParameter.cs Code/Parameter
git mv ByteParameter.cs Code/Parameter
git mv CharParameter.cs Code/Parameter
git mv ClientTypeParameter.cs Code/Parameter
git mv CodeParameter.cs Code/Parameter
git mv CodeunitParameter.cs Code/Parameter
git mv DateFormulaParameter.cs Code/Parameter
git mv DateParameter.cs Code/Parameter
git mv DateTimeParameter.cs Code/Parameter
git mv DecimalParameter.cs Code/Parameter
git mv DefaultLayoutParameter.cs Code/Parameter
git mv DialogParameter.cs Code/Parameter
git mv DotNetParameter.cs Code/Parameter
git mv DurationParameter.cs Code/Parameter
git mv EventParameters.cs Code/Parameter
git mv ExecutionModeParameter.cs Code/Parameter
git mv FieldRefParameter.cs Code/Parameter
git mv FileParameter.cs Code/Parameter
git mv FilterPageBuilderParameter.cs Code/Parameter
git mv FunctionParameters.cs Code/Parameter
git mv GuidParameter.cs Code/Parameter
git mv InStreamParameter.cs Code/Parameter
git mv IntegerParameter.cs Code/Parameter
git mv KeyRefParameter.cs Code/Parameter
git mv NotificationParameter.cs Code/Parameter
git mv NotificationScopeParameter.cs Code/Parameter
git mv ObjectTypeParameter.cs Code/Parameter
git mv OcxParameter.cs Code/Parameter
git mv OptionParameter.cs Code/Parameter
git mv OutStreamParameter.cs Code/Parameter
git mv PageParameter.cs Code/Parameter
git mv Parameter.cs Code/Parameter
git mv Parameters.cs Code/Parameter
git mv QueryParameter.cs Code/Parameter
git mv RecordIDParameter.cs Code/Parameter
git mv RecordParameter.cs Code/Parameter
git mv RecordRefParameter.cs Code/Parameter
git mv ReportFormatParameter.cs Code/Parameter
git mv ReportParameter.cs Code/Parameter
git mv TableConnectionTypeParameter.cs Code/Parameter
git mv TestPageParameter.cs Code/Parameter
git mv TestPermissionsParameter.cs Code/Parameter
git mv TestRequestPageParameter.cs Code/Parameter
git mv TextEncodingParameter.cs Code/Parameter
git mv TextParameter.cs Code/Parameter
git mv TimeParameter.cs Code/Parameter
git mv TransactionTypeParameter.cs Code/Parameter
git mv VariantParameter.cs Code/Parameter
git mv XmlPortParameter.cs Code/Parameter
git mv ActionVariable.cs Code/Variable
git mv AutomationVariable.cs Code/Variable
git mv BigIntegerVariable.cs Code/Variable
git mv BigTextVariable.cs Code/Variable
git mv BinaryVariable.cs Code/Variable
git mv BooleanVariable.cs Code/Variable
git mv ByteVariable.cs Code/Variable
git mv CharVariable.cs Code/Variable
git mv ClientTypeVariable.cs Code/Variable
git mv Code.cs Code/Variable
git mv CodeunitVariable.cs Code/Variable
git mv CodeVariable.cs Code/Variable
git mv DateFormulaVariable.cs Code/Variable
git mv DateTimeVariable.cs Code/Variable
git mv DateVariable.cs Code/Variable
git mv DecimalVariable.cs Code/Variable
git mv DefaultLayoutVariable.cs Code/Variable
git mv DialogVariable.cs Code/Variable
git mv DotNetVariable.cs Code/Variable
git mv DurationVariable.cs Code/Variable
git mv Event.cs Code/Variable
git mv EventVariables.cs Code/Variable
git mv ExecutionModeVariable.cs Code/Variable
git mv FieldRefVariable.cs Code/Variable
git mv FileVariable.cs Code/Variable
git mv FilterPageBuilderVariable.cs Code/Variable
git mv Function.cs Code/Variable
git mv FunctionVariables.cs Code/Variable
git mv GlobalVariables.cs Code/Variable
git mv GuidVariable.cs Code/Variable
git mv InStreamVariable.cs Code/Variable
git mv IntegerVariable.cs Code/Variable
git mv KeyRefVariable.cs Code/Variable
git mv LocalVariables.cs Code/Variable
git mv NotificationScopeVariable.cs Code/Variable
git mv NotificationVariable.cs Code/Variable
git mv ObjectTypeVariable.cs Code/Variable
git mv OcxVariable.cs Code/Variable
git mv OptionVariable.cs Code/Variable
git mv OutStreamVariable.cs Code/Variable
git mv PageVariable.cs Code/Variable
git mv QueryVariable.cs Code/Variable
git mv RecordIDVariable.cs Code/Variable
git mv RecordRefVariable.cs Code/Variable
git mv RecordVariable.cs Code/Variable
git mv ReportFormatVariable.cs Code/Variable
git mv ReportVariable.cs Code/Variable
git mv SourceField.cs Code/Variable
git mv StringExtensionMethods.cs Code/Variable
git mv TableConnectionTypeVariable.cs Code/Variable
git mv TestPageVariable.cs Code/Variable
git mv TestPermissionsVariable.cs Code/Variable
git mv TextConstant.cs Code/Variable
git mv TextEncodingVariable.cs Code/Variable
git mv TextVariable.cs Code/Variable
git mv TimeVariable.cs Code/Variable
git mv TransactionTypeVariable.cs Code/Variable
git mv Trigger.cs Code/Variable
git mv TriggerVariables.cs Code/Variable
git mv Variable.cs Code/Variable
git mv Variables.cs Code/Variable
git mv VariantVariable.cs Code/Variable
git mv XmlPortVariable.cs Code/Variable
git mv Codeunit.cs Codeunit
git mv CodeunitProperties.cs Codeunit
git mv Codeunits.cs Codeunit
git mv CodeunitSubType.cs Codeunit
git mv IHasCode.cs Contracts
git mv IHasCodeLines.cs Contracts
git mv IHasDimensions.cs Contracts
git mv IHasName.cs Contracts
git mv IHasOptionString.cs Contracts
git mv IHasProperties.cs Contracts
git mv IHasRequestPage.cs Contracts
git mv INode.cs Contracts
git mv IPage.cs Contracts
git mv IPageExtensionMethods.cs Contracts
git mv IProperties.cs Contracts
git mv AutoCaptionExtensionMethods.cs Extension
git mv ExtensionMethods.cs Extension
git mv IDManagementExtensionMethods.cs Extension
git mv Collection.cs Generic
git mv KeyedAndNamedContainer.cs Generic
git mv KeyedContainer.cs Generic
git mv KeyedItem.cs Generic
git mv DeltaNode.cs MenuSuite
git mv GroupNode.cs MenuSuite
git mv ItemNode.cs MenuSuite
git mv MenuItemDepartmentCategory.cs MenuSuite
git mv MenuItemRunObjectType.cs MenuSuite
git mv MenuNode.cs MenuSuite
git mv MenuSuite.cs MenuSuite
git mv MenuSuiteDeltaNodeProperties.cs MenuSuite
git mv MenuSuiteGroupNodeProperties.cs MenuSuite
git mv MenuSuiteItemNodeProperties.cs MenuSuite
git mv MenuSuiteMenuNodeProperties.cs MenuSuite
git mv MenuSuiteNode.cs MenuSuite
git mv MenuSuiteNodes.cs MenuSuite
git mv MenuSuiteProperties.cs MenuSuite
git mv MenuSuiteRootNodeProperties.cs MenuSuite
git mv MenuSuites.cs MenuSuite
git mv RootNode.cs MenuSuite
mkdir Page/Action
mkdir Page/Control
git mv Page.cs Page
git mv PageProperties.cs Page
git mv Pages.cs Page
git mv PageType.cs Page
git mv ActionList.cs Page/Action
git mv PageAction.cs Page/Action
git mv PageActionBase.cs Page/Action
git mv PageActionContainer.cs Page/Action
git mv PageActionContainerProperties.cs Page/Action
git mv PageActionContainerType.cs Page/Action
git mv PageActionGroup.cs Page/Action
git mv PageActionGroupProperties.cs Page/Action
git mv PageActionProperties.cs Page/Action
git mv PageActionScope.cs Page/Action
git mv PageActionSeparator.cs Page/Action
git mv PageActionSeparatorProperties.cs Page/Action
git mv ControlList.cs Page/Control
git mv PageControl.cs Page/Control
git mv PageControlBase.cs Page/Control
git mv PageControlContainer.cs Page/Control
git mv PageControlContainerProperties.cs Page/Control
git mv PageControlContainerType.cs Page/Control
git mv PageControlGroup.cs Page/Control
git mv PageControlGroupLayout.cs Page/Control
git mv PageControlGroupProperties.cs Page/Control
git mv PageControlGroupType.cs Page/Control
git mv PageControlPart.cs Page/Control
git mv PageControlPartProperties.cs Page/Control
git mv PageControlPartType.cs Page/Control
git mv PageControlProperties.cs Page/Control
git mv PageControls.cs Page/Control
mkdir Property/Enumeration
mkdir Property/Implementation
mkdir Property/Type
git mv ObjectProperties.cs Property
git mv Properties.cs Property
git mv AccessByPermissionObjectType.cs Property/Enumeration
git mv BlankNumbers.cs Property/Enumeration
git mv CalcFormulaMethod.cs Property/Enumeration
git mv DateMethod.cs Property/Enumeration
git mv DefaultLayout.cs Property/Enumeration
git mv Direction.cs Property/Enumeration
git mv ExtendedDataType.cs Property/Enumeration
git mv ExternalAccess.cs Property/Enumeration
git mv FieldClass.cs Property/Enumeration
git mv FormatEvaluate.cs Property/Enumeration
git mv Gesture.cs Property/Enumeration
git mv Importance.cs Property/Enumeration
git mv MaxOccurs.cs Property/Enumeration
git mv MinOccurs.cs Property/Enumeration
git mv MissingAction.cs Property/Enumeration
git mv Occurrence.cs Property/Enumeration
git mv Order.cs Property/Enumeration
git mv PaperSource.cs Property/Enumeration
git mv Position.cs Property/Enumeration
git mv PreviewMode.cs Property/Enumeration
git mv PromotedCategory.cs Property/Enumeration
git mv ReadState.cs Property/Enumeration
git mv RecordSecurityFiltering.cs Property/Enumeration
git mv RunPageMode.cs Property/Enumeration
git mv StandardDayTimeUnit.cs Property/Enumeration
git mv Style.cs Property/Enumeration
git mv SystemPartID.cs Property/Enumeration
git mv TestPermissions.cs Property/Enumeration
git mv TextEncoding.cs Property/Enumeration
git mv TotalsMethod.cs Property/Enumeration
git mv TransactionModel.cs Property/Enumeration
git mv UpdatePropagation.cs Property/Enumeration
git mv AccessByPermissionProperty.cs Property/Implementation
git mv ActionListProperty.cs Property/Implementation
git mv AutoFormatTypeProperty.cs Property/Implementation
git mv BlankNumbersProperty.cs Property/Implementation
git mv BlobSubTypeProperty.cs Property/Implementation
git mv BooleanProperty.cs Property/Implementation
git mv CalcFormulaProperty.cs Property/Implementation
git mv CodeunitSubTypeProperty.cs Property/Implementation
git mv ColumnFilterProperty.cs Property/Implementation
git mv ControlListProperty.cs Property/Implementation
git mv DataItemLinkTypeProperty.cs Property/Implementation
git mv DataItemQueryElementTableFilterProperty.cs Property/Implementation
git mv DateMethodProperty.cs Property/Implementation
git mv DecimalPlaces.cs Property/Implementation
git mv DecimalPlacesProperty.cs Property/Implementation
git mv DefaultLayoutProperty.cs Property/Implementation
git mv DirectionProperty.cs Property/Implementation
git mv DurationProperty.cs Property/Implementation
git mv EventSubscriberInstanceProperty.cs Property/Implementation
git mv ExtendedDataTypeProperty.cs Property/Implementation
git mv ExternalAccessProperty.cs Property/Implementation
git mv FieldClassProperty.cs Property/Implementation
git mv FieldList.cs Property/Implementation
git mv FieldListProperty.cs Property/Implementation
git mv FormatEvaluateProperty.cs Property/Implementation
git mv GestureProperty.cs Property/Implementation
git mv ImportanceProperty.cs Property/Implementation
git mv LinkField.cs Property/Implementation
git mv LinkFields.cs Property/Implementation
git mv LinkFieldsProperty.cs Property/Implementation
git mv MaxOccursProperty.cs Property/Implementation
git mv MenuItemDepartmentCategoryProperty.cs Property/Implementation
git mv MenuItemRunObjectTypeProperty.cs Property/Implementation
git mv MethodTypeProperty.cs Property/Implementation
git mv MinOccursProperty.cs Property/Implementation
git mv MultiLanguageEntry.cs Property/Implementation
git mv MultiLanguageProperty.cs Property/Implementation
git mv MultiLanguageValue.cs Property/Implementation
git mv NullableBigIntegerProperty.cs Property/Implementation
git mv NullableBooleanProperty.cs Property/Implementation
git mv NullableDateProperty.cs Property/Implementation
git mv NullableDateTimeProperty.cs Property/Implementation
git mv NullableDecimalProperty.cs Property/Implementation
git mv NullableGuidProperty.cs Property/Implementation
git mv NullableIntegerProperty.cs Property/Implementation
git mv NullableTimeProperty.cs Property/Implementation
git mv NullableValueProperty.cs Property/Implementation
git mv ObjectProperty.cs Property/Implementation
git mv ObjectReference.cs Property/Implementation
git mv OccurrenceProperty.cs Property/Implementation
git mv OptionOrdinalValuesProperty.cs Property/Implementation
git mv OptionStringProperty.cs Property/Implementation
git mv PageActionContainerTypeProperty.cs Property/Implementation
git mv PageActionScopeProperty.cs Property/Implementation
git mv PageControlContainerTypeProperty.cs Property/Implementation
git mv PageControlGroupLayoutProperty.cs Property/Implementation
git mv PageControlGroupTypeProperty.cs Property/Implementation
git mv PageControlPartTypeProperty.cs Property/Implementation
git mv PageReferenceProperty.cs Property/Implementation
git mv PageTypeProperty.cs Property/Implementation
git mv PaperSourceProperty.cs Property/Implementation
git mv Permission.cs Property/Implementation
git mv Permissions.cs Property/Implementation
git mv PermissionsProperty.cs Property/Implementation
git mv PreviewModeProperty.cs Property/Implementation
git mv PromotedCategoryProperty.cs Property/Implementation
git mv Property.cs Property/Implementation
git mv QueryDataItemLinkProperty.cs Property/Implementation
git mv QueryOrderByLinesProperty.cs Property/Implementation
git mv ReadStateProperty.cs Property/Implementation
git mv ReferenceProperty.cs Property/Implementation
git mv ReportDataItemLinkProperty.cs Property/Implementation
git mv RunObject.cs Property/Implementation
git mv RunObjectLink.cs Property/Implementation
git mv RunObjectLinkLine.cs Property/Implementation
git mv RunObjectLinkProperty.cs Property/Implementation
git mv RunObjectProperty.cs Property/Implementation
git mv RunPageModeProperty.cs Property/Implementation
git mv ScopedTriggerProperty.cs Property/Implementation
git mv SemiColonSeparatedStringProperty.cs Property/Implementation
git mv SIFTLevelsProperty.cs Property/Implementation
git mv SourceFieldProperty.cs Property/Implementation
git mv SqlDataTypeProperty.cs Property/Implementation
git mv SqlJoinTypeProperty.cs Property/Implementation
git mv StandardDayTimeUnitProperty.cs Property/Implementation
git mv StringProperty.cs Property/Implementation
git mv StyleProperty.cs Property/Implementation
git mv SystemPartIDProperty.cs Property/Implementation
git mv TableFieldTypeProperty.cs Property/Implementation
git mv TableReferenceProperty.cs Property/Implementation
git mv TableRelationProperty.cs Property/Implementation
git mv TableTypeProperty.cs Property/Implementation
git mv TableView.cs Property/Implementation
git mv TableViewProperty.cs Property/Implementation
git mv TagList.cs Property/Implementation
git mv TagListProperty.cs Property/Implementation
git mv TestFunctionTypeProperty.cs Property/Implementation
git mv TestIsolationProperty.cs Property/Implementation
git mv TestPermissionsProperty.cs Property/Implementation
git mv TextEncodingProperty.cs Property/Implementation
git mv TextTypeProperty.cs Property/Implementation
git mv TotalsMethodProperty.cs Property/Implementation
git mv TransactionModelProperty.cs Property/Implementation
git mv TransactionTypeProperty.cs Property/Implementation
git mv TriggerProperty.cs Property/Implementation
git mv UpdatePropagationProperty.cs Property/Implementation
git mv UpgradeFunctionTypeProperty.cs Property/Implementation
git mv ValueProperty.cs Property/Implementation
git mv XmlPortEncodingProperty.cs Property/Implementation
git mv XmlPortFormatProperty.cs Property/Implementation
git mv XmlPortNamespacesProperty.cs Property/Implementation
git mv XmlPortNodeDataTypeProperty.cs Property/Implementation
git mv XmlVersionNoProperty.cs Property/Implementation
git mv AccessByPermission.cs Property/Type
git mv AutoFormatType.cs Property/Type
git mv BlobSubType.cs Property/Type
git mv DataItemLinkType.cs Property/Type
git mv EventType.cs Property/Type
git mv MethodType.cs Property/Type
git mv RunObjectType.cs Property/Type
git mv SqlDataType.cs Property/Type
git mv SqlJoinType.cs Property/Type
git mv TextType.cs Property/Type
git mv TransactionType.cs Property/Type
git mv ColumnQueryElement.cs Query
git mv ColumnQueryElementProperties.cs Query
git mv DataItemQueryElement.cs Query
git mv FilterQueryElement.cs Query
git mv FilterQueryElementProperties.cs Query
git mv Queries.cs Query
git mv Query.cs Query
git mv QueryDataItemLink.cs Query
git mv QueryDataItemLinkLine.cs Query
git mv QueryElement.cs Query
git mv QueryElements.cs Query
git mv QueryOrderByDirection.cs Query
git mv QueryOrderByLine.cs Query
git mv QueryOrderByLines.cs Query
git mv QueryProperties.cs Query
git mv QuerySecurityFiltering.cs Query
git mv ColumnReportElement.cs Report
git mv ColumnReportElementProperties.cs Report
git mv DataItemReportElement.cs Report
git mv RdlData.cs Report
git mv Report.cs Report
git mv ReportDataItemLink.cs Report
git mv ReportDataItemLinkLine.cs Report
git mv ReportElement.cs Report
git mv ReportElements.cs Report
git mv ReportLabel.cs Report
git mv ReportLabelProperties.cs Report
git mv ReportLabels.cs Report
git mv ReportProperties.cs Report
git mv Reports.cs Report
git mv RequestPage.cs Report
git mv RequestPageProperties.cs Report
git mv WordLayout.cs Report
mkdir Table/Field
mkdir Table/Key
mkdir Table/Relation
git mv DataItemQueryElementProperties.cs Table
git mv Table.cs Table
git mv TableProperties.cs Table
git mv Tables.cs Table
git mv TableType.cs Table
mkdir Table/Field/Properties
git mv BigIntegerTableField.cs Table/Field
git mv BinaryTableField.cs Table/Field
git mv BlobTableField.cs Table/Field
git mv BooleanTableField.cs Table/Field
git mv CalcFormula.cs Table/Field
git mv CalcFormulaTableFilterLine.cs Table/Field
git mv CodeTableField.cs Table/Field
git mv DateFormulaTableField.cs Table/Field
git mv DateTableField.cs Table/Field
git mv DateTimeTableField.cs Table/Field
git mv DecimalTableField.cs Table/Field
git mv DurationTableField.cs Table/Field
git mv ExtendedTableFilterType.cs Table/Field
git mv GuidTableField.cs Table/Field
git mv IntegerTableField.cs Table/Field
git mv MediaSetTableField.cs Table/Field
git mv MediaTableField.cs Table/Field
git mv OptionTableField.cs Table/Field
git mv RecordIDTableField.cs Table/Field
git mv TableField.cs Table/Field
git mv TableFieldGroup.cs Table/Field
git mv TableFieldGroups.cs Table/Field
git mv TableFields.cs Table/Field
git mv TableFilterLine.cs Table/Field
git mv TableFilterTableField.cs Table/Field
git mv TextTableField.cs Table/Field
git mv TextTableFieldProperties.cs Table/Field
git mv TimeTableField.cs Table/Field
git mv BigIntegerTableFieldProperties.cs Table/Field/Properties
git mv BinaryTableFieldProperties.cs Table/Field/Properties
git mv BlobTableFieldProperties.cs Table/Field/Properties
git mv BooleanTableFieldProperties.cs Table/Field/Properties
git mv CalcFormulaTableFilter.cs Table/Field/Properties
git mv CodeTableFieldProperties.cs Table/Field/Properties
git mv DataItemReportElementProperties.cs Table/Field/Properties
git mv DateFormulaTableFieldProperties.cs Table/Field/Properties
git mv DateTableFieldProperties.cs Table/Field/Properties
git mv DateTimeTableFieldProperties.cs Table/Field/Properties
git mv DecimalTableFieldProperties.cs Table/Field/Properties
git mv DurationTableFieldProperties.cs Table/Field/Properties
git mv GuidTableFieldProperties.cs Table/Field/Properties
git mv IntegerTableFieldProperties.cs Table/Field/Properties
git mv MediaSetTableFieldProperties.cs Table/Field/Properties
git mv MediaTableFieldProperties.cs Table/Field/Properties
git mv OptionTableFieldProperties.cs Table/Field/Properties
git mv RecordIDTableFieldProperties.cs Table/Field/Properties
git mv TableFieldGroupProperties.cs Table/Field/Properties
git mv TableFilter.cs Table/Field/Properties
git mv TableFilterTableFieldProperties.cs Table/Field/Properties
git mv TableFilterType.cs Table/Field/Properties
git mv TimeTableFieldProperties.cs Table/Field/Properties
git mv SIFTLevel.cs Table/Key
git mv SIFTLevelComponent.cs Table/Key
git mv SIFTLevelComponents.cs Table/Key
git mv SIFTLevels.cs Table/Key
git mv TableKey.cs Table/Key
git mv TableKeyProperties.cs Table/Key
git mv TableKeys.cs Table/Key
git mv TableRelation.cs Table/Relation
git mv TableRelationCondition.cs Table/Relation
git mv TableRelationConditions.cs Table/Relation
git mv TableRelationLine.cs Table/Relation
git mv TableRelationTableFilter.cs Table/Relation
git mv TableRelationTableFilterLine.cs Table/Relation
git mv XmlPort.cs XmlPort
git mv XmlPortEncoding.cs XmlPort
git mv XmlPortFieldAttribute.cs XmlPort
git mv XmlPortFieldAttributeProperties.cs XmlPort
git mv XmlPortFieldElement.cs XmlPort
git mv XmlPortFieldElementProperties.cs XmlPort
git mv XmlPortFormat.cs XmlPort
git mv XmlPortNamespace.cs XmlPort
git mv XmlPortNamespaces.cs XmlPort
git mv XmlPortNode.cs XmlPort
git mv XmlPortNodeAndSourceType.cs XmlPort
git mv XmlPortNodes.cs XmlPort
git mv XmlPortProperties.cs XmlPort
git mv XmlPorts.cs XmlPort
git mv XmlPortTableAttribute.cs XmlPort
git mv XmlPortTableAttributeProperties.cs XmlPort
git mv XmlPortTableElement.cs XmlPort
git mv XmlPortTableElementProperties.cs XmlPort
git mv XmlPortTextAttribute.cs XmlPort
git mv XmlPortTextAttributeProperties.cs XmlPort
git mv XmlPortTextElement.cs XmlPort
git mv XmlPortTextElementProperties.cs XmlPort
git mv XmlVersionNo.cs XmlPort
