// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    public enum FunctionReturnValueType
    {
        Boolean,
        Integer,
        Decimal,
        BigInteger,
        Char,
        Text,
        Code,
        Date,
        Time,
        Duration,
        DateTime,
        Binary,
        Guid,
        Byte,
        Option,
    }

}
