// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class LinkField
    {
        public LinkField(int field, int referenceField)
        {
            Field = field;
            ReferenceField = referenceField;
        }

        public int Field
        {
            get;
            protected set;
        }

        public int ReferenceField
        {
            get;
            protected set;
        }
    }
}
