// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class MenuSuite : Object
    {
        public MenuSuite(int id, String name)
            : base(id, name)
        {
            Properties = new MenuSuiteProperties();
            Nodes = new MenuSuiteNodes();
        }

        public override ObjectType Type
        {
            get
            {
                return ObjectType.MenuSuite;
            }
        }

        public MenuSuiteProperties Properties
        {
            get;
            protected set;
        }

        public MenuSuiteNodes Nodes
        {
            get;
            protected set;
        }

        public override Properties AllProperties
        {
            get
            {
                return Properties;
            }
        }
    }
}
