// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public class MenuSuiteNodes : IEnumerable<MenuSuiteNode>
    {
        private Dictionary<Guid,MenuSuiteNode> innerList = new Dictionary<Guid,MenuSuiteNode>();

        internal MenuSuiteNodes()
        {
        }

        public T Add<T>(T item) where T: MenuSuiteNode
        {
            innerList.Add(item.ID, item);
            return item;
        }

        public bool Remove(Guid id)
        {
            return innerList.Remove(id);
        }

        public IEnumerator<MenuSuiteNode> GetEnumerator()
        {
            return innerList.Values.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return innerList.Values.GetEnumerator();
        }
    }
}
