// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public class MultiLanguageValue : IEnumerable<MultiLanguageEntry>
    {
        private Dictionary<String, MultiLanguageEntry> innerList = new Dictionary<String, MultiLanguageEntry>();

        internal MultiLanguageValue()
        {
        }

        public void Set(String languageID, String value)
        {
            Unset(languageID);
            innerList.Add(languageID, new MultiLanguageEntry(languageID, value));
        }

        public void Reset()
        {
            innerList.Clear();
        }

        public bool Unset(String languageID)
        {
            return innerList.Remove(languageID);
        }

        public IEnumerator<MultiLanguageEntry> GetEnumerator()
        {
            return innerList.Values.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return innerList.Values.GetEnumerator();
        }
    }
}
