// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
	[Serializable]
	public abstract partial class Parameter : KeyedItem<int>, IHasName
	{
		private bool var;
		private string dimensions;
		private string name;

		internal Parameter(bool var, int id, string name)
		{
			ID = id;
			this.name = name;
			this.var = var;
		}

		public abstract ParameterType Type
		{
			get;
		}

		public bool Var
		{
			get
			{
				return this.var;
			}
		}

		public string Dimensions
		{
			get
			{
				return this.dimensions;
			}
			set
			{
				this.dimensions = value;
			}
		}

		public string Name
		{
			get
			{
				return this.name;
			}
		}


		public string GetName()
		{
			return Name;
		}
	}
}
