// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    public enum ParameterType
    {
        Action,
        Automation,
        BigInteger,
        BigText,
        Binary,
        Boolean,
        Byte,
        Char,
        Code,
        Codeunit,
        DateFormula,
        Date,
        DateTime,
        Decimal,
        Dialog,
        DotNet,
        Duration,
        ExecutionMode,
        FieldRef,
        File,
        Guid,
        InStream,
        Integer,
        KeyRef,
        Ocx,
        Option,
        OutStream,
        Page,
        Query,
        RecordID,
        Record,
        RecordRef,
        Report,
        TestPage,
        TestRequestPage,
        Text,
        Time,
        TransactionType,
        Variant,
        XmlPort,
    }

}
