// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class Permission
    {
        internal Permission(int tableID, bool readPermission, bool insertPermission, bool modifyPermission, bool deletePermission)
        {
            TableID = tableID;
            ReadPermission = readPermission;
            InsertPermission = insertPermission;
            ModifyPermission = modifyPermission;
            DeletePermission = deletePermission;
        }

        public int TableID
        {
            get;
            protected set;
        }

        public bool ReadPermission
        {
            get;
            protected set;
        }

        public bool InsertPermission
        {
            get;
            protected set;
        }

        public bool ModifyPermission
        {
            get;
            protected set;
        }

        public bool DeletePermission
        {
            get;
            protected set;
        }
    }
}
