// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class QueryDataItemLinkLine
    {
        private String field;
        private String referenceTable;
        private String referenceField;

        public QueryDataItemLinkLine(String field, String referenceTable, String referenceField)
        {
            this.field = field;
            this.referenceField = referenceField;
            this.referenceTable = referenceTable;
        }

        public String Field
        {
            get
            {
                return this.field;
            }
        }

        public String ReferenceTable
        {
            get
            {
                return this.referenceTable;
            }
        }

        public String ReferenceField
        {
            get
            {
                return this.referenceField;
            }
        }

    }
}
