// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public abstract partial class QueryElement : KeyedItem<int>, IHasName, IHasProperties
    {
        public QueryElement(int id, String name, int? indentationLevel)
        {
            ID = id;
            IndentationLevel = indentationLevel;
            Name = name;
        }

        public abstract QueryElementType Type
        {
            get;
        }

        public String Name
        {
            get;
            protected set;
        }

        public int? IndentationLevel
        {
            get;
            protected set;
        }

        public QueryElements Container
        {
            get;
            internal set;
        }

        public string GetName()
        {
            return Name;
        }

        public abstract Properties AllProperties
        {
            get;
        }
    }
}
