// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public class QueryElements : IntegerKeyedAndNamedContainer<QueryElement>
    {
        internal QueryElements(Query query)
        {
            Query = query;
        }
        }

        public override void ValidateName(QueryElement item)
        {
            TestNameUnique(item);
        }

        public Query Query
        {
            get;
            protected set;
        }
    }
}
