// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class QueryDataItemLinkLine
    {
        private string field;
        private string referenceTable;
        private string referenceField;

        public QueryDataItemLinkLine(string field, string referenceTable, string referenceField)
        {
            this.field = field;
            this.referenceField = referenceField;
            this.referenceTable = referenceTable;
        }

        public string Field
        {
            get
            {
                return this.field;
            }
        }

        public string ReferenceTable
        {
            get
            {
                return this.referenceTable;
            }
        }

        public string ReferenceField
        {
            get
            {
                return this.referenceField;
            }
        }

    }
}
