// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class Query : Object, IHasCode
    {
        public Query(Int32 id, String name)
            : base(id, name)
        {
            Properties = new QueryProperties();
            Elements = new QueryElements();
            Code = new Code();
        }

        public override ObjectType Type
        {
            get
            {
                return ObjectType.Query;
            }
        }

        public QueryProperties Properties
        {
            get;
            protected set;
        }

        public QueryElements Elements
        {
            get;
            protected set;
        }

        public Code Code
        {
            get;
            protected set;
        }

        public override Properties AllProperties
        {
            get
            {
                return Properties;
            }
        }
    }
}
