// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
	[Serializable]
	public abstract partial class ReportElement : KeyedItem<int>, IHasName, IHasProperties
	{
		private int? indentationLevel;
		private string name;

		public ReportElement(int id, int? indentationLevel)
		{
			ID = id;
			this.indentationLevel = indentationLevel;
		}

		public abstract ReportElementType Type
		{
			get;
		}

		public int? IndentationLevel
		{
			get
			{
				return this.indentationLevel;
			}
		}

		public string Name
		{
			get
			{
				return this.name;
			}
			set
			{
				this.name = value;
			}
		}

		public abstract Properties AllProperties
		{
			get;
		}

		public  string GetName()
		{
			return Name;
		}
	}
}
