// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
	[Serializable]
	public partial class ReportLabel : KeyedItem<int>, IHasName
	{
		private string name;
		private ReportLabelProperties properties = new ReportLabelProperties();

		public ReportLabel(int id, string name)
		{
			ID = id;
			this.name = name;
		}

		public string Name
		{
			get
			{
				return this.name;
			}
		}

		public ReportLabelProperties Properties
		{
			get
			{
				return this.properties;
			}
		}


		public  string GetName()
		{
			return Name;
		}
	}
}
