// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class SIFTLevelComponent
    {
        public SIFTLevelComponent(string fieldName, string aspect)
        {
            Aspect = aspect;
            FieldName = fieldName;
        }

        public string FieldName
        {
            get;
            protected set;
        }

        public string Aspect
        {
            get;
            protected set;
        }
    }
}
