// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class SIFTLevelComponent
    {
        private string fieldName;
        private string aspect;

        public SIFTLevelComponent(string fieldName, string aspect)
        {
            this.aspect = aspect;
            this.fieldName = fieldName;
        }

        public string FieldName
        {
            get
            {
                return this.fieldName;
            }
        }

        public string Aspect
        {
            get
            {
                return this.aspect;
            }
        }

    }
}
