// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class SourceField
    {
        private String fieldName;
        private String tableVariableName;

        internal SourceField()
        {
        }

        public String FieldName
        {
            get
            {
                return this.fieldName;
            }
            set
            {
                this.fieldName = value;
            }
        }

        public String TableVariableName
        {
            get
            {
                return this.tableVariableName;
            }
            set
            {
                this.tableVariableName = value;
            }
        }

    }
}
