// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public class TableFields : IEnumerable<TableField>
    {
        private Dictionary<Int32,TableField> innerList = new Dictionary<Int32,TableField>();

        internal TableFields()
        {
        }

        public T Add<T>(T item) where T: TableField
        {
            innerList.Add(item.No, item);
            return item;
        }

        public bool Remove(Int32 no)
        {
            return innerList.Remove(no);
        }

        public IEnumerator<TableField> GetEnumerator()
        {
            return innerList.Values.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return innerList.Values.GetEnumerator();
        }
    }
}
