// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public class TableKeys : Collection<TableKey>
    {
        internal TableKeys()
        {
        }

        public new TableKey Add(TableKey item)
        {
            this.InsertItem(Count, item);
            return item;
        }

        public new TableKey Insert(int index, TableKey item)
        {
            this.InsertItem(index, item);
            return item;
        }
    }
}
