// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    public enum TableFieldType
    {
        BigInteger,
        Binary,
        BLOB,
        Boolean,
        Code,
        DateFormula,
        Date,
        DateTime,
        Decimal,
        Duration,
        Guid,
        Integer,
        Option,
        RecordID,
        TableFilter,
        Text,
        Time,
    }

}
