// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class TableRelationLine
    {
        private TableRelationConditions conditions = new TableRelationConditions();
        private string fieldName;
        private TableRelationTableFilter tableFilter = new TableRelationTableFilter();
        private string tableName;

        public TableRelationLine(string tableName)
        {
            this.tableName = tableName;
        }

        public TableRelationConditions Conditions
        {
            get
            {
                return this.conditions;
            }
        }

        public string FieldName
        {
            get
            {
                return this.fieldName;
            }
            set
            {
                this.fieldName = value;
            }
        }

        public TableRelationTableFilter TableFilter
        {
            get
            {
                return this.tableFilter;
            }
        }

        public string TableName
        {
            get
            {
                return this.tableName;
            }
        }

    }
}
