// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    public enum TestFunctionType
    {
        Normal,
        Test,
        MessageHandler,
        ConfirmHandler,
        StrMenuHandler,
        PageHandler,
        ModalPageHandler,
        ReportHandler,
        RequestPageHandler,
#if NAV2016
        FilterPageHandler,
        HyperlinkHandler
#endif
    }

}
