// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class XmlPortRequestPage : IHasPageControls
    {
        private PageControls controls = new PageControls();
        private XmlPortRequestPageProperties properties = new XmlPortRequestPageProperties();

        internal XmlPortRequestPage()
        {
        }

        public PageControls Controls
        {
            get
            {
                return this.controls;
            }
        }

        public XmlPortRequestPageProperties Properties
        {
            get
            {
                return this.properties;
            }
        }

    }
}
