// --------------------------------------------------------------------------------
// <auto-generated>
//      This code was generated by a tool.
//
//      Changes to this file may cause incorrect behaviour and will be lost if
//      the code is regenerated.
// </auto-generated>
// --------------------------------------------------------------------------------

using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;

namespace UncommonSense.CBreeze.Core
{
    [Serializable]
    public partial class XmlPortRequestPage : IHasPageControls
    {

        internal XmlPortRequestPage()
        {
            Properties = new XmlPortRequestPageProperties();
            Controls = new PageControls();
        }

        public PageControls Controls
        {
            get;
            protected set;
        }

        public XmlPortRequestPageProperties Properties
        {
            get;
            protected set;
        }

    }
}
